### ISSUE TITLE
Support for Optional Material in Course

### ISSUE THREAD

**Issue by vinukumar-vs** [project-sunbird/sunbird-portal#8664]
# Project Details

**What is Sunbird-Portal?**

[Sunbird](http://sunbird.org/) is a next-generation scalable open-source learning solution for teachers and tutors. Built for the 21st century with [state-of-the-art technology](http://www.sunbird.org/architecture/views/physical/), Sunbird runs natively in [cloud/mobile environments](http://www.sunbird.org/features/). The [open-source governance](https://github.com/Sunbird-Ed/SunbirdEd-portal/blob/master/LICENSE) of Sunbird allows a massive community of nation-builders to co-create and extend the solution in novel ways.

https://github.com/Sunbird-Ed/SunbirdEd-portal#what-is-sunbird

# Features to be implemented
Context: As a creator I would like to attach reference material in a collection which might relate to understand the subject or topic better but is not mandatory to consume to complete the syllabus. 
Also these optional materials can be added to any trackable collection where the creator believes it helps in growing the user’s knowledge in the subject though it doesn’t contribute on the progress.

**What exists:**

- All the contents in the course has to consume to get 100% progress.
- If user has partially complete the content also, it will be affecting the progress of the course.

**What needs to be build**
- As a creator of the course should able to select any content in the hierarchy as optional content.
- The contents which are selected as optional, these contents should be considered for progress of the course.
-  There should be clear differentiation of optional material & regular contents showing in the TOC of the course.

# Learning Path

### Complexity 
Medium

### Skills Required
Angular

### Name of Mentors
@rajeevsathish @swayangjit 

### Project size
8 Weeks

# Product Set Up
https://github.com/Sunbird-Ed/SunbirdEd-portal#readme

# Acceptance Criteria

- [ ] As a creator, I should be able to add optional material in the trackable (or non trackable collection- make sure this flow doesn’t break) as a reference study material

- [ ] The Optional material shouldn’t contribute to the users' progress % of the trackable collection and hence doesn’t contribute in the completion certificate criteria. For ex., if a course (which is a trackable collection) has 3 resources - 2 mandatory and 1 optional. If the batch which is offering this course has a certificate issue criteria = ‘issue certs to all users whose course progress is 100%’ then the certificate should be issued as soon as the user completes the 2 mandatory resources. 

- [ ] The optional material shouldn’t contribute to the final score calculation of the collection and hence doesn’t contribute in the merit certificate criteria. For ex., if a course (which is a trackable collection) has 3 resources - 2 mandatory and 1 optional. The optional resource is a course assessment. In this scenario, the certificate issue criteria should not show the option to issue certs based on score. Any batches which are offering this course should only be able to issue completion certificates.  In the course ToC page, user should be able to view their latest attempt score. In the course progress exhaust as well the assessment score details should be shown.

- [ ] Additional material can be a content within a module or all of them can be bundled together as a module.

- [ ] Once a course is published, no further structural changes are allowed including adding optional material.

- [ ] Backward compatibility of mobile apps to handle optional material in older mobile apps needs to be handled - if the user is on an older mobile app version which is not compatible with this change then when the user clicks on the optional material then the user should be informed that they should upgrade the app to view the content. In the course ToC, the optional material label should be shown in the older mobile app versions.

- [ ] When the creator marks a content/module as an optional material during creation, add a prefix “Additional Material” before the content name on the course tile on course toc and course player page 

- [ ] If any collection contain an optional material show “The additional material doesn’t contribute to the progress% or final score”  next to the progress bar in the course toc please confirm this

# Milestones

- [ ] Creation of the contents by marking them as optional in the editors while creating the course.
- [ ] Differentiating of optional materials & regular contents in the consumption portal.

**Comment by Shruti3004** [comment]
Hey @vinukumar-vs  thanks for detailing this out, can you please remove or add the details in out of scope section. Thanks!

**Comment by Kapil650** [comment]
@rajeevsathish @swayangjit  I am interested in this project and looking forward to contributing to this work in the C4GT 2023.
My Name is Kapil, MCA final year CRSU student with knowledge of Angular, React and Node as provided in curriculum of MCA and also done certifications to enhance my Knowlege about MERN Stack. Also Learning AWS to gain understanding about cloud.

**Comment by Deepali-1508** [comment]
@vinukumar-vs  I wanted to express my interest in the project you described involving the implementation of optional material functionality in an e-learning course. The requirements you have outlined align perfectly with my skills . I am eager to contribute in this project and collaborate with the team to deliver a high-quality solution.
